raw_cloud_filter:
    apply_filter: true
    filter_boat_points: true
    filter_range: true
    filter_intensity: true

    boat_length: 4.0
    boat_width: 3.0
    max_height: 2.0
    max_xy_range: 60.0
    min_intensity: 5
