raw_cloud_filter:
    apply_filter: true
    filter_boat_points: true
    filter_range: true
    filter_intensity: true
    debug_cloud: true

    boat_length: 1.2 # meters
    boat_width: 1.4 # meters
    max_height: 0.3 # meters - we are not going to consider this due to the inclination the boat might have
    max_xy_range: 20.0 # meters
    min_intensity: 10

pointcloud2scan:
    angle_resolution: 5.0 # degrees 

livox2scan:
    input_frame: "livox_frame"
    output_frame: "base_link"
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 180.0 # degrees
    pitch: 0.0 # degrees
    yaw: 0.0 # degrees

ping2scan:
    input_frame: "ping_frame"
    output_frame: "base_link"
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
